# Generated by Django 5.1.4 on 2024-12-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Waiting', max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('service_description', models.TextField()),
                ('token_number', models.CharField(max_length=255, unique=True)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
